defaults:
  - _self_
  - model: small_3.5_to_3
  - override hydra/launcher: submitit_slurm

ngpus: 4
tokens: 11

image_size: [128, 128, 64]   # next_data_size*data.crop_size

training:
  batch_size: 4
  accum: 1
  n_iters: 1300001
  snapshot_freq: 1000
  log_freq: 50
  eval_freq: 1000
  snapshot_freq_for_preemption: 10
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  dataset: kitti360
  train_data_path: '/data/hqj/pyramid-discrete-diffusion/data/kitti360_512_512_128/kitti360_quantized_512_512_128/Train'
  quantized_train_data_path: '/data/hqj/pyramid-discrete-diffusion/data/kitti360_256_256_64/kitti360_quantized_256_256_64/Train'
  valid_data_path: '/data/hqj/pyramid-discrete-diffusion/data/kitti360_512_512_128/kitti360_quantized_512_512_128/Val'
  quantized_valid_data_path: '/data/hqj/pyramid-discrete-diffusion/data/kitti360_256_256_64/kitti360_quantized_256_256_64/Val'
  infer_data_path: ''
  quantized_infer_data_path: ''
  data_argumentation: true
  prev_stage: 's_3'  # choices: none, s_1, s_2
  next_stage: 's_4'  # choices: s_1, s_2, s_3
  prev_data_size: [256, 256, 64]
  next_data_size: [512, 512, 128]
  prev_scene_path: ''
  infer_data_source: 'dataset'
  crop_size: [0.25, 0.25, 0.5]

graph:
  type: absorb_relay
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 4
  perplexity: True
  perplexity_batch_size: 32

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    # dir: exp_local/${data.dataset}_3.5_to_3_distribute_relay/${now:%Y.%m.%d}/${now:%H%M%S}
    dir: exp_local/kitti360_3_to_4_distribute_relay_try2/2025.01.23/150458
  sweep:
    # dir: exp_local/${data.dataset}_3.5_to_3_distribute_relay/${now:%Y.%m.%d}/${now:%H%M%S}
    dir: exp_local/kitti360_3_to_4_distribute_relay_try2/2025.01.23/150458
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    # timeout_min: 10079
    partition: g40x
    account: stanford
    mem_gb: 96
    cpus_per_task: 5
    gpus_per_node: ${ngpus}
    constraint: null
